name: build

permissions:
  contents: read

on:
  push:
    branches: [ main, build, coveralls ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 14, 16, 18 ]
    name: Node ${{ matrix.node }} build
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: npm ci
        run: npm ci
      - name: npm test
        run: npm test
      - name: coveralls
        uses: coverallsapp/github-action@v1
        with:
          flag-name: node-${{ matrix.node }}
          parallel: true

  report:
    needs: build
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
    - name: coveralls report
      uses: coverallsapp/github-action@v1
      with:
        parallel-finished: true
        carryforward: "node-14,node-16,node-18"
